import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    findJobs: 'Find Jobs',
    freelance: 'Freelance Services',
    hiringHub: 'Hiring Hub',
    myApplications: 'My Applications',
    postJob: 'Post a Job',
    login: 'Log in',
    signup: 'Sign up',
    logout: 'Log out',
    allNepal: 'All Nepal (नेपाल भर)',
    kathmandu: 'Kathmandu (काठमाडौं)',
    pokhara: 'Pokhara (पोखरा)',
    lalitpur: 'Lalitpur (ललितपुर)',
    remote: 'Remote / Overseas',
    welcomeBack: 'Welcome back',
    loginIntro: 'Log in to KAAM Nepal to apply, hire, or manage your gigs.',
    username: 'Username',
    password: 'Password',
    loggingIn: 'Logging in...',
    logIn: 'Log In',
    newToKaam: 'New to KAAM Nepal?',
    createAccount: 'Create an account',
    joinKaam: 'Join KAAM Nepal',
    registerIntro: 'Create an account as a job seeker/freelancer or as an employer.',
    firstName: 'First Name',
    lastName: 'Last Name',
    district: 'District',
    skills: 'Skills (comma-separated)',
    creatingAccount: 'Creating account...',
    createAccountButton: 'Create Account',
    alreadyAccount: 'Already have an account?',
    searchJobs: 'Search Jobs',
    jobsNearYou: 'Jobs Near You',
    viewAll: 'View all',
    popularGigs: 'Popular Freelance Gigs',
    browseAll: 'Browse all',
    hiringNepal: 'Hiring in Nepal?',
    jobSeekerMode: 'Job Seeker',
    employerMode: 'Employer',
    allSectors: 'All Sectors',
    allTypes: 'All Types',
    skilledTrades: 'Skilled Trades & Construction',
    techRemote: 'Tech, Remote & IT',
    hospitality: 'Hospitality & Culinary',
    logistics: 'Transport & Logistics',
    healthcare: 'Healthcare & Diagnostics',
    fullTime: 'Full-time',
    partTime: 'Part-time',
    dailyWage: 'Daily Wage',
    contract: 'Contract',
    newestFirst: 'Newest First',
    highestPay: 'Highest Pay',
    jobOpenings: 'Job Openings',
    openings: 'Openings',
    verifiedJobs: 'Verified local employers, daily gigs & remote contracts',
    loadingJobs: 'Loading jobs...',
    noJobs: 'No jobs match your filters yet.',
    searchPlaceholder: 'Role, trade skill, or keyword...',
    jobDescription: 'Job Description',
    jobLocation: 'Job Location',
    getDirections: 'Get directions',
    pay: 'Pay',
    negotiable: 'Negotiable',
    loginToApply: 'Log in to Apply',
    coverNote: 'Short cover note (optional)',
    cvLink: 'CV or resume link (optional)',
    portfolioLink: 'Portfolio link (optional)',
    submitting: 'Submitting...',
    applyNow: 'Apply Now',
    applicationSubmitted: 'Application submitted!',
    postVacancy: 'Post a Job Vacancy',
    jobTitle: 'Job Title',
    companyName: 'Company Name',
    description: 'Description',
    workLocation: 'Work location or address',
    optional: 'optional',
    rateType: 'Rate Type',
    publishJob: 'Publish Job',
    publishing: 'Publishing...',
    applicantPipeline: 'Applicant Pipeline (ATS)',
    managePipeline: 'Manage your job posts and move applicants through your pipeline.',
    loadingHub: 'Loading hiring hub...',
    viewApplicant: 'View applicant details',
    chatApplicant: 'Chat with applicant',
    rateSeeker: 'Rate job seeker',
    yourJobPosts: 'Your Job Posts',
    noJobPosts: "You haven't posted any jobs yet.",
    myApps: 'My Applications',
    trackApps: 'Track your applications and message employers through KAAM Nepal.',
    loadingApps: 'Loading applications...',
    noApps: 'You have not applied to any jobs yet.',
    chatEmployer: 'Chat with employer',
    employerChat: 'Employer chat',
    send: 'Send',
    sending: 'Sending...',
    writeMessage: 'Write a message...',
    postGig: 'Post a Freelance Gig',
    gigTitle: 'Gig Title',
    category: 'Category',
    rate: 'Rate (NPR)',
    deliveryDays: 'Delivery Days',
    publishGig: 'Publish Gig',
    jobType: 'Job Type',
    other: 'Other', design: 'Design & Creative', dev: 'Programming & Tech', writing: 'Writing & Translation', trades: 'Home & Trade Services', tutoring: 'Tutoring & Lessons',
    applied: 'Applied', shortlisted: 'Shortlisted', interview: 'Interview', offered: 'Offered', hired: 'Hired', rejected: 'Rejected',
    freelanceServices: 'Freelance & Trade Services', loadingGigs: 'Loading gigs...', searchGigs: 'Search gigs...',
    sendProposal: 'Send Proposal', proposalSent: 'Proposal sent!', proposalMessage: 'Describe what you need...', budget: 'Your budget (NPR, optional)',
  },
  ne: {
    findJobs: 'जागिर खोज्नुहोस्',
    freelance: 'फ्रिलान्स सेवाहरू',
    hiringHub: 'भर्ती केन्द्र',
    myApplications: 'मेरा आवेदनहरू',
    postJob: 'जागिर पोस्ट गर्नुहोस्',
    login: 'लग इन',
    signup: 'साइन अप',
    logout: 'लग आउट',
    allNepal: 'सम्पूर्ण नेपाल',
    kathmandu: 'काठमाडौं',
    pokhara: 'पोखरा',
    lalitpur: 'ललितपुर',
    remote: 'रिमोट / विदेश',
    welcomeBack: 'फेरि स्वागत छ',
    loginIntro: 'आवेदन दिन, भर्ती गर्न वा आफ्ना सेवाहरू व्यवस्थापन गर्न KAAM Nepal मा लग इन गर्नुहोस्।',
    username: 'प्रयोगकर्ता नाम',
    password: 'पासवर्ड',
    loggingIn: 'लग इन हुँदैछ...',
    logIn: 'लग इन गर्नुहोस्',
    newToKaam: 'KAAM Nepal मा नयाँ हुनुहुन्छ?',
    createAccount: 'खाता बनाउनुहोस्',
    joinKaam: 'KAAM Nepal मा सामेल हुनुहोस्',
    registerIntro: 'जागिर खोज्ने/फ्रिलान्सर वा रोजगारदाताको रूपमा खाता बनाउनुहोस्।',
    firstName: 'पहिलो नाम',
    lastName: 'थर',
    district: 'जिल्ला',
    skills: 'सीपहरू (अल्पविरामले छुट्याउनुहोस्)',
    creatingAccount: 'खाता बनाउँदैछ...',
    createAccountButton: 'खाता बनाउनुहोस्',
    alreadyAccount: 'पहिले नै खाता छ?',
    searchJobs: 'जागिर खोज्नुहोस्',
    jobsNearYou: 'तपाईं नजिकका जागिरहरू',
    viewAll: 'सबै हेर्नुहोस्',
    popularGigs: 'लोकप्रिय फ्रिलान्स सेवाहरू',
    browseAll: 'सबै हेर्नुहोस्',
    hiringNepal: 'नेपालमा भर्ती गर्दै हुनुहुन्छ?',
    jobSeekerMode: 'जागिर खोज्ने',
    employerMode: 'रोजगारदाता',
    allSectors: 'सबै क्षेत्र',
    allTypes: 'सबै प्रकार',
    skilledTrades: 'सीपमूलक व्यापार तथा निर्माण',
    techRemote: 'प्रविधि तथा रिमोट',
    hospitality: 'आतिथ्य तथा खाना',
    logistics: 'यातायात तथा व्यवस्थापन',
    healthcare: 'स्वास्थ्य सेवा',
    fullTime: 'पूर्णकालीन',
    partTime: 'अंशकालीन',
    dailyWage: 'दैनिक ज्याला',
    contract: 'करार',
    newestFirst: 'नयाँ पहिले',
    highestPay: 'उच्च पारिश्रमिक',
    jobOpenings: 'जागिरका अवसरहरू',
    openings: 'अवसर',
    verifiedJobs: 'प्रमाणित स्थानीय रोजगारदाता, दैनिक काम र रिमोट करार',
    loadingJobs: 'जागिरहरू लोड हुँदैछन्...',
    noJobs: 'तपाईंका फिल्टरसँग मिल्ने जागिर छैन।',
    searchPlaceholder: 'भूमिका, सीप वा शब्द खोज्नुहोस्...',
    jobDescription: 'जागिरको विवरण',
    jobLocation: 'जागिरको स्थान',
    getDirections: 'बाटो हेर्नुहोस्',
    pay: 'पारिश्रमिक',
    negotiable: 'छलफल गर्न सकिने',
    loginToApply: 'आवेदन दिन लग इन गर्नुहोस्',
    coverNote: 'छोटो आवेदन टिप्पणी (ऐच्छिक)',
    cvLink: 'CV वा रिजुमे लिंक (ऐच्छिक)',
    portfolioLink: 'पोर्टफोलियो लिंक (ऐच्छिक)',
    submitting: 'पठाउँदैछ...',
    applyNow: 'आवेदन दिनुहोस्',
    applicationSubmitted: 'आवेदन पठाइयो!',
    postVacancy: 'जागिरको अवसर पोस्ट गर्नुहोस्',
    jobTitle: 'जागिरको शीर्षक',
    companyName: 'कम्पनीको नाम',
    description: 'विवरण',
    workLocation: 'कामको स्थान वा ठेगाना',
    optional: 'ऐच्छिक',
    rateType: 'दरको प्रकार',
    publishJob: 'जागिर प्रकाशित गर्नुहोस्',
    publishing: 'प्रकाशित हुँदैछ...',
    applicantPipeline: 'आवेदक प्रक्रिया (ATS)',
    managePipeline: 'आफ्ना जागिरहरू व्यवस्थापन गर्नुहोस् र आवेदकहरूलाई प्रक्रियामा अघि बढाउनुहोस्।',
    loadingHub: 'भर्ती केन्द्र लोड हुँदैछ...',
    viewApplicant: 'आवेदकको विवरण हेर्नुहोस्',
    chatApplicant: 'आवेदकसँग कुराकानी',
    rateSeeker: 'जागिर खोज्नेलाई मूल्याङ्कन गर्नुहोस्',
    yourJobPosts: 'तपाईंका जागिर पोस्टहरू',
    noJobPosts: 'तपाईंले अहिलेसम्म जागिर पोस्ट गर्नुभएको छैन।',
    myApps: 'मेरा आवेदनहरू',
    trackApps: 'आफ्ना आवेदनहरू हेर्नुहोस् र रोजगारदातासँग कुराकानी गर्नुहोस्।',
    loadingApps: 'आवेदनहरू लोड हुँदैछन्...',
    noApps: 'तपाईंले अहिलेसम्म कुनै जागिरमा आवेदन दिनुभएको छैन।',
    chatEmployer: 'रोजगारदातासँग कुराकानी',
    employerChat: 'रोजगारदातासँग कुराकानी',
    send: 'पठाउनुहोस्',
    sending: 'पठाउँदैछ...',
    writeMessage: 'सन्देश लेख्नुहोस्...',
    postGig: 'फ्रिलान्स सेवा पोस्ट गर्नुहोस्',
    gigTitle: 'सेवाको शीर्षक',
    category: 'श्रेणी',
    rate: 'दर (रु.)',
    deliveryDays: 'डेलिभरी दिन',
    publishGig: 'सेवा प्रकाशित गर्नुहोस्',
    jobType: 'जागिरको प्रकार',
    other: 'अन्य', design: 'डिजाइन तथा सिर्जना', dev: 'प्रोग्रामिङ तथा प्रविधि', writing: 'लेखन तथा अनुवाद', trades: 'घर तथा सीप सेवा', tutoring: 'ट्युसन तथा शिक्षा',
    applied: 'आवेदन गरिएको', shortlisted: 'छानिएको', interview: 'अन्तर्वार्ता', offered: 'प्रस्ताव गरिएको', hired: 'नियुक्त', rejected: 'अस्वीकृत',
    freelanceServices: 'फ्रिलान्स तथा सीप सेवा', loadingGigs: 'सेवाहरू लोड हुँदैछन्...', searchGigs: 'सेवा खोज्नुहोस्...',
    sendProposal: 'प्रस्ताव पठाउनुहोस्', proposalSent: 'प्रस्ताव पठाइयो!', proposalMessage: 'तपाईंलाई के चाहिन्छ लेख्नुहोस्...', budget: 'तपाईंको बजेट (रु., ऐच्छिक)',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('kaam_language') || 'en')
  const changeLanguage = (nextLanguage) => {
    setLanguage(nextLanguage)
    localStorage.setItem('kaam_language', nextLanguage)
  }
  const t = (key) => translations[language][key] || translations.en[key] || key

  return <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
