# Generated by Django 5.0.6 on 2026-09-19 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('sector', models.CharField(choices=[('trade', 'Skilled Trades & Construction'), ('tech', 'Tech, Remote & IT'), ('hospitality', 'Hospitality & Culinary'), ('logistics', 'Transport & Logistics'), ('health', 'Healthcare & Diagnostics'), ('other', 'Other')], default='other', max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('daily_wage', 'Daily Wage'), ('contract', 'Contract'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('district', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara'), ('lalitpur', 'Lalitpur'), ('biratnagar', 'Biratnagar'), ('nepalgunj', 'Nepalgunj'), ('remote', 'Remote / Overseas'), ('other', 'Other')], default='kathmandu', max_length=20)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('fixed', 'Fixed / Project')], default='monthly', max_length=20)),
                ('skills_required', models.CharField(blank=True, help_text='Comma-separated', max_length=500)),
                ('is_verified_escrow', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
