# Generated by Django 5.0.6 on 2026-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
    ]
