# Generated by Django 5.0.6 on 2026-09-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
