# Generated by Django 5.0.6 on 2026-09-19 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('design', 'Design & Creative'), ('dev', 'Programming & Tech'), ('writing', 'Writing & Translation'), ('trades', 'Home & Trade Services'), ('tutoring', 'Tutoring & Lessons'), ('other', 'Other')], default='other', max_length=20)),
                ('rate', models.PositiveIntegerField(help_text='Rate in NPR')),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price')], default='fixed', max_length=10)),
                ('delivery_days', models.PositiveIntegerField(default=3)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated', max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_proposals', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='gigs.gig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
